### ISSUE TITLE
Release 1.0.2 APK does not install. 

### ISSUE THREAD

**Issue by joshuamking** [gauravk95/bubble-navigation#1]
Pixel 3 XL running Pie. 

![screenshot_20190302-055219](https://user-images.githubusercontent.com/5152470/53680915-b5e2e500-3caf-11e9-823b-1e49a14a5c6b.png)

**Comment by gauravk95** [comment]
Have you enabled "**install apps from unknown sources**"?
Usually found in Security or Privacy Setting...

**Comment by joshuamking** [comment]
Lol yes, I think you have some kind of signing issue.
But from the gifs it look pretty cool!

**Comment by gauravk95** [comment]
I have rebuild the apk and updated the Sample App. You may try it out...

**Comment by joshuamking** [comment]
Yep, it works! Thanks! Nice work!
