### ISSUE TITLE
how to change the color of  item backgroud when switching,current color is white

### ISSUE THREAD

**Issue by dary123** [gauravk95/bubble-navigation#10]
how to change the color of  item backgroud when switching,current color is white

**Comment by gauravk95** [comment]
You can use **TransitionDrawable** for that. A transition drawable has a start and an end state.
Refer the Readme and [TopBarActivity](https://github.com/gauravk95/bubble-navigation/blob/master/app/src/main/res/layout/activity_top_bar.xml)

This is how a TransitionDrawable looks
```xml
<?xml version="1.0" encoding="utf-8"?>
<transition xmlns:android="http://schemas.android.com/apk/res/android">
    <item android:drawable="@drawable/start_state" />
    <item android:drawable="@drawable/end_state" />
</transition>
```
The start and end state can be a any shape or vector asset of you choice of color...
