### ISSUE TITLE
RTL support ??

### ISSUE THREAD

**Issue by gaiththewolf** [gauravk95/bubble-navigation#13]
when rtl interface icon and text not showing :(

**Comment by gaiththewolf** [comment]
works fine sorry

**Comment by rayansys** [comment]
when rtl interface icon and text not showing and icon not in right side

**Comment by shubhamnandanwar** [comment]
@gaiththewolf how you fixed it?

**Comment by charafboulmerk** [comment]
Hello friends
i solved the problem by just adding this line : android:layoutDirection="ltr"
to your view 
com.gauravk.bubblenavigation.BubbleNavigationConstraintView

and here is an example 

`      <com.gauravk.bubblenavigation.BubbleNavigationConstraintView
            android:id="@+id/top_navigation_constraint"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:background="@color/dark_gray"
            android:elevation="0dp"
            android:paddingTop="5dp"
            android:paddingBottom="5dp"
            android:paddingLeft="10dp"
            android:paddingRight="10dp"
            android:layoutDirection="ltr"
            app:bnc_mode="inside"
            app:hideOnScroll="true">`
