### ISSUE TITLE
Add Real fragments

### ISSUE THREAD

**Issue by rajam1215** [gauravk95/bubble-navigation#21]
How to Add fragments instead of colors

your code
ArrayList<ScreenSlidePageFragment> fragList = new ArrayList<>();
        fragList.add(ScreenSlidePageFragment.newInstance(getString(R.string.home), R.color.red_inactive));
        fragList.add(ScreenSlidePageFragment.newInstance(getString(R.string.search), R.color.blue_inactive));

i want

ArrayList<ScreenSlidePageFragment> fragList = new ArrayList<>();
        fragList.add(new firstFragement());
4 more.

please look in to it

**Comment by adilkhanoff** [comment]
@rajam1215 Hello. Can you help me? How you add your own fragments? I cannot understand how to do this. Help me please!

**Comment by rajam1215** [comment]
We can change fragement like this

bubbleNavigation.setNavigationChangeListener(new BubbleNavigationChangeListener() {
            @Override
            public void onNavigationChanged(View view, int position) {
                if(position == 0){
loadFragment(new XyzFragment());
}
else if(position == 1){
loadFragment(new AbcFragment());
}
            }
        });

// call this method out side of main function // on create 
/**
     * loading fragment into FrameLayout
     *
     * @param fragment
     */
    private void loadFragment(Fragment fragment) {
        // load fragment
        FragmentTransaction transaction = getSupportFragmentManager().beginTransaction();
        transaction.replace(R.id.frame_container, fragment);
        transaction.commit();
    }

**Comment by adilkhanoff** [comment]
Thank you a lot. I did it because of you!
