### ISSUE TITLE
Nullpointer when trying to inital start with other then first item

### ISSUE THREAD

**Issue by matecode** [gauravk95/bubble-navigation#3]
I'm trying to start wit another then the first item in Bubble-Navigation, but when i try to `setCurrentActiveItem` in `onViewCreated` I get a NullPointer (see below). How can I achieve to initial select another than the first item?

The exception:
```
java.lang.NullPointerException: Attempt to invoke virtual method 'int java.util.ArrayList.size()' on a null object reference
        at com.gauravk.bubblenavigation.BubbleNavigationConstraintView.setCurrentActiveItem(BubbleNavigationConstraintView.java:294)
```

This is my code, nothing very special here, just trying to keep viewpager and navigation in sync and have the possibility to start with last item:
```
    override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
        adapter = Adapter(childFragmentManager)
        cv_navigation.setNavigationChangeListener { navView, position ->
            viewPager.setCurrentItem(position,true)
        }
        viewPager.adapter = adapter
        viewPager.addOnPageChangeListener(object: ViewPager.OnPageChangeListener {
            override fun onPageScrollStateChanged(state: Int) {
            }

            override fun onPageScrolled(position: Int, positionOffset: Float, positionOffsetPixels: Int) {
            }

            override fun onPageSelected(position: Int) {
                    cv_navigation.setCurrentActiveItem(position);
            }
        })
        if (arguments != null && savedInstanceState == null && arguments!!.getBoolean(USE_LAST)) {
            viewPager.currentItem = adapter!!.count - 1;
        }
    }

```

**Comment by gauravk95** [comment]
Hi,
If you would like to change the initial selection, you can set the  `app:bt_active="true"` property for `BubbleToggleView`  inside the XML to the Navigation Element that you want to make active. 
Note: if multiple child elements have `bt_active` set as true, the first one is preferred and others are automatically deactivate.

Also, set the start element of the view pager to the one you require...
`viewPager.setCurrentItem(position,false)`

As of the crash, it's not expected...I will get on to it ASAP...

Maybe you can try calling it in `onActivityCreated()`, see if that helps...
