### ISSUE TITLE
Set custom font

### ISSUE THREAD

**Issue by MrNouri** [gauravk95/bubble-navigation#5]
Thanks for this great library.
How can i set custom font for texts?

**Comment by gauravk95** [comment]
**setTypeface(Typeface typeface)** is meant for this purpose.

Eg:
```java
Typeface typeface = ResourcesCompat.getFont(this, R.font.app_font);
mLinearNavigation.setTypeface(typeface);
```

**Comment by Tanuj1108** [comment]
how can i use bottom nevigation to change activity in bottom click

**Comment by gauravk95** [comment]
> how can i use bottom nevigation to change activity in bottom click
> becouse there is not any option to change state
> 
> BubbleNavigationLinearView bubbleNavigation = (BubbleNavigationLinearView)findViewById(R.id.bottom_navigation_view_linear);
> 
> ```
>     bubbleNavigation.setNavigationChangeListener(new BubbleNavigationChangeListener() {
>         @Override
>         public void onNavigationChanged(View view, int position) {
>             switch (position.getItemId())
>         }
>     });
> ```
> getItemId showing error so how can i choose id to change activity in on click

Please open a new Issue as this is not the right place to comment an issue....I would suggest you to delete this one...

Will answer your queried their...

**Comment by MrNouri** [comment]
Hi dear, i write below codes for set font. but after run app show me below error

**My codes:**
```
                val typeface = ResourcesCompat.getFont(this, R.font.iransans_font)
                bubbleNavBar.setTypeface(typeface)
```

**Error :** 
```
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.Iterator java.util.ArrayList.iterator()' on a null object reference
        at com.gauravk.bubblenavigation.BubbleNavigationLinearView.setTypeface(BubbleNavigationLinearView.java:209)
        at com.app.applisttestapp.UI.Home.Activity.HomeActivity.onCreate(HomeActivity.kt:47)
        at android.app.Activity.performCreate(Activity.java:6020)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1105)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2284)
```

how can i fix it?

**Comment by gauravk95** [comment]
Seems like an issue in Library...

For the time being, you can call `setTypeface()` after the view has been laid out. 
I guess setting it in onStart() will help, but its definitely not recommended.

I will come up with the Fix ASAP.

**Comment by MrNouri** [comment]
Thanks for fix this bug.
but after set `typeFace` show me incomplete Farsi worlds!
in below image, tab name is **هفته** but show me **هفتـ**
![15](https://user-images.githubusercontent.com/44635442/55670278-b61a6580-5897-11e9-90e1-ecb990ae85cb.jpg)

or for other tab, this tab is **ثبت نام شده** but show me **ثبت نام شـ**
![16](https://user-images.githubusercontent.com/44635442/55670287-ccc0bc80-5897-11e9-8d48-ef23aade4444.jpg)

can you fix this bug for RTL languages ?

**Comment by MrNouri** [comment]
Can you help me fix this problem?

**Comment by gauravk95** [comment]
Hi, I have not much experience in RTL Languages. Sorry, but can't help as of now.
If you may have any fix, I would be happy to accept a Pull Request.
