### ISSUE TITLE
new intent in bottom navigation

### ISSUE THREAD

**Issue by Tanuj1108** [gauravk95/bubble-navigation#6]
how can i use bottom nevigation to change activity in bottom click
becouse there is not any option to change state

BubbleNavigationLinearView bubbleNavigation = (BubbleNavigationLinearView)findViewById(R.id.bottom_navigation_view_linear);

    bubbleNavigation.setNavigationChangeListener(new BubbleNavigationChangeListener() {
        @Override
        public void onNavigationChanged(View view, int position) {
            switch (position.getItemId())
        }
    });
getItemId showing error so how can i choose id to change activity in on click

 @gauravk95
 Owner

**Comment by gauravk95** [comment]
You can use the current active navigation position to change the activity. Note, that the positions are relative to the order of the child Nav items represented by **BubbleToggleView**
```java
bubbleNavigation.setNavigationChangeListener(new BubbleNavigationChangeListener() {
    @Override
    public void onNavigationChanged(View view, int position) {
        switch (position){
                case 0: launchFirstActivity();
                break;
                case 1: launchSecondActivity();
                break;
         }
    }
});
```
**OR**

If you have set layout id's for the child Nav items represented by **BubbleToggleView**
```java
bubbleNavigation.setNavigationChangeListener(new BubbleNavigationChangeListener() {
    @Override
    public void onNavigationChanged(View view, int position) {
        switch (view.getId()){
                case R.id.first_activity_toggle: launchFirstActivity();
                break;
                case R.id.second_activity_toggle: launchSecondActivity();
                break;
         }
    }
});
```

**Comment by Tanuj1108** [comment]
BubbleNavigationChangeListener bubbleNavigation = (BubbleNavigationChangeListener) findViewById(R.id.bottom_navigation_view_linear);

        bubbleNavigation.onNavigationChanged(new BubbleNavigationChangeListener() {
            @Override
            public void onNavigationChanged(View view, int position) {
                switch (view.getId()){
                    case R.id.l_item_search:
                        Intent in=new Intent(getBaseContext(),Secondactivity.class);
                        startActivity(in);
                        overridePendingTransition(0, 0);
                        break;
                }
            }
        });



it is again showing error

**Comment by Tanuj1108** [comment]
BubbleNavigationChangeListener bubbleNavigation = (BubbleNavigationChangeListener) findViewById(R.id.bottom_navigation_view_linear);

        bubbleNavigation.setNavigationChangeListener(new BubbleNavigationChangeListener() {
            @Override
            public void onNavigationChanged(View view, int position) {
                switch (view.getId()){
                    case R.id.l_item_search:
                        Intent in=new Intent(getBaseContext(),Secondactivity.class);
                        startActivity(in);
                        overridePendingTransition(0, 0);
                        break;
                }
            }
        });


in this .setNavigationChangeListener showing error so what can i do

**Comment by gauravk95** [comment]
Please post the Logcat/snippet of the error. Without that I cannot debug the issue...

It seems like the `overridePendingTransition(0,0)` might be cause problems

**Comment by Tanuj1108** [comment]
![android screenshot](https://user-images.githubusercontent.com/33170928/54303861-f153ac80-45e9-11e9-8ccc-3d5c8f52ef62.jpg)

please see this at .setNavigationChangeListener is showing an error

**Comment by gauravk95** [comment]
Your usage is wrong!

`R.id.bottom_navigation_view_linear` is of the type **BubbleNavigationLinearView** or it can be of type **BubbleNavigationConstraintView**

Use like this
```java
BubbleNavigationLinearView bubbleNavigation = findViewById(R.id.bottom_navigation_view_linear);
bubbleNavigation.setNavigationChangeListener(new BubbleNavigationChangeListener() {
        @Override
        public void onNavigationChanged(View view, int position) {
            switch (view.getId()){
                case R.id.l_item_search:
                    Intent in=new Intent(getBaseContext(),Secondactivity.class);
                    startActivity(in);
                    break;
            }
        }
```

**Comment by Tanuj1108** [comment]
thanks it's done
