### ISSUE TITLE
Add badges

### ISSUE THREAD

**Issue by MrNouri** [gauravk95/bubble-navigation#7]
Hi, how can i add badges to items?

**Comment by MrNouri** [comment]
can you say me when you want add this feature?
because i want use this library into my application.
thanks ❤️

**Comment by gauravk95** [comment]
Hi,
I have been very busy, but you can expect it by this weekend.
Sry for the delay!

**Comment by MrNouri** [comment]
it's great! thanks my friend ❤️

**Comment by dary123** [comment]
I want it too

**Comment by atthapon-k** [comment]
Any update about this? thanks

**Comment by gauravk95** [comment]
I have started working on it. Will release the update soon.

**Comment by gauravk95** [comment]
Have add support for badges in the new version 1.0.6.
